name: "GDScript Lint"

on:
  push:
    paths:
      - '**.gd'
  pull_request:
    paths:
      - '**.gd'

jobs:
  lint:
    name: Run gdlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          
      - name: Install gdtoolkit
        run: pip install gdtoolkit
        
      - name: Run gdlint
        run: gdlint .
